### ISSUE TITLE
'where' attribute on exceptions?

### ISSUE THREAD

**Issue by alexmojaki** [cknd/stackprinter#18]
What is the purpose of this code?

https://github.com/cknd/stackprinter/blob/fb51f4dbf42e23da80d1d333ceefdd05bb4b3183/stackprinter/frame_formatting.py#L129-L132

**Comment by cknd** [comment]
It adds some debug info to an internal failsafe mechanism.

Bit more context: I decided early on that the worst thing this library could do would be to swallow an exception in your application code if ever it crashes itself (even a long chain of "during handling..." tracebacks seems too obtrusive).

So the `format_exc_info` code is wrapped in a catchall that restores a classical traceback if any of my stuff went wrong, headed by short message with a little bit of debug info. That's where the monkeypatched `where` comes in, it notes which frame (~= file & lineno) we were trying to format when it happened 
see here for more https://github.com/cknd/stackprinter/blob/ef58d179625bf4a4201cd69a42693d8fc3f78267/stackprinter/formatting.py#L199-L202

**Comment by cknd** [comment]
I'll add a comment there

**Comment by alexmojaki** [comment]
Ah OK, I searched for `.where` and didn't find anything, the `getattr` threw me off but of course you need it.

Shouldn't functions other than `format_exc_info` have that exception handling?

I think that code should be reduced to just `exc.where = frame`. `str(frame)` will already show the filename, code name, and lineno anyway.

**Comment by cknd** [comment]
The trouble is that the formatters are so careless wrt their input types - `frame` can be a FrameInfo tuple (aka a "predigested" frame), and those have quite verbose `str`s. Not anymore though: https://github.com/cknd/stackprinter/pull/21

**Comment by alexmojaki** [comment]
Of course, I was thinking about it backwards. Your approach in #21 is good.
