### ISSUE TITLE
Inspect the AST instead of iterating through the tokenized source

### ISSUE THREAD

**Issue by cknd** [cknd/stackprinter#22]
Currently, to find out where in the code which variable names occur, I traverse the code token-by-token and apply a sort of ad hoc stack machine that detects stuff like the beginning of function definitions, dot attributes etc. This is clearly nuts, and purely a path effect (= it's how ipython's ultratb does it, and then my scope expanded and here we are).
https://github.com/cknd/stackprinter/blob/master/stackprinter/source_inspection.py

This approach works for now, but it has hit its limits. For example, I'd like to ignore the left-hand side of named arguments in function calls.

Goals:
- annotate in a piece of code where each variable name occurs, exactly like the current system, but with less of a home made rube goldberg machine behind it.
- keep the ability to rerender the original code character by character as it appears in the source file (incl extra whitespaces, comment ascii art etc -- so people can visually recognize their code)

**Comment by alexmojaki** [comment]
I'm working on a library of the kind that was discussed in better-exceptions and IPython and planning on using it here. It's entirely AST based and satisfies these requirements. It uses https://github.com/gristlabs/asttokens for the second point and https://github.com/alexmojaki/executing for some extra functionality.

**Comment by cknd** [comment]
sounds very promising!

**Comment by alexmojaki** [comment]
If you're interested in a sneak peek or following progress, I've just created the repo here: https://github.com/alexmojaki/stack_data

Still lots of work to do though.

**Comment by cknd** [comment]
👀

**Comment by cknd** [comment]
the solution is #52
