### ISSUE TITLE
Ignore certain exceptions in `set_excepthook`

### ISSUE THREAD

**Issue by tsoernes** [cknd/stackprinter#25]
I'd like to make a feature request for passing a list of exceptions to `set_excepthook` that are either ignored and printed in the standard format or in a minimal style. Useful for `KeyboardInterrupt` because that's user-triggered and a detailed exception output is often not wanted.

**Comment by cknd** [comment]
That should totally exist, yes

**Comment by cknd** [comment]
merged #31

**Comment by cknd** [comment]
(..and released in https://pypi.org/project/stackprinter/0.2.4 :tada:)
