### ISSUE TITLE
No Colors in Windows (git-bash) / No option to enable colors

### ISSUE THREAD

**Issue by divyanshuParihar265** [cknd/stackprinter#49]
**I am new to this package , so i might not know something**

I was using this lib on windows and tried changing styles but this is not showing my err styles.

![image](https://user-images.githubusercontent.com/58904683/126027716-20b1ef8c-4da4-48c4-9b4e-fbe4b40ad238.png)
code:
```
import numpy
import stackprinter


def dangerous_function(blub):
    return sorted(blub, key=lambda xs: sum(xs))

try:
    somelist = [[1,2], [3,4]]
    anotherlist = [['5', 6]]
    spam = numpy.zeros((3,3))
    dangerous_function(somelist + anotherlist)
except:
    stackprinter.show(style='darkbg', source_lines=4)

```
is there anything is need in order to get colors working on windows.

**Comment by divyanshuParihar265** [comment]
I tried this on git-bash between

**Comment by cknd** [comment]
Hi! I don't have a windows machine to test this, but I can help you with the relevant keyword: What you need is a terminal that supports _ANSI color codes_. It sounds like the standard windows terminal didn't have this feature until recently and you need to enable it somehow https://www.google.com/search?q=windows+console+ansi+color+codes

**Comment by divyanshuParihar265** [comment]
https://github.com/gulpjs/gulp/issues/1292#issuecomment-258090062
I will try this.. later

**Comment by cknd** [comment]
I'll close this here for now - feel free to reopen if there is a problem with the color codes sent by stackprinter!

**Comment by divyanshuParihar265** [comment]
Looks like this problem only occur when i use git-bash inside vscode . because normal gitbash can handle colours
![image](https://user-images.githubusercontent.com/58904683/126056687-8a03af3a-2735-4272-b6a3-43c3684b0c08.png)


Inside vs code.

![image](https://user-images.githubusercontent.com/58904683/126056692-5a37616b-43e5-412e-b308-f1fd5a3de018.png)
