### ISSUE TITLE
Add a way to redact some variables

### ISSUE THREAD

**Issue by Schnouki** [cknd/stackprinter#50]
Hey there,

I'm considering using stackprinter at my company to help with some debugging tasks. Its output would be in our logs, and thus be sent to DataDog. But we don't really want to do that unless we have more control over the output.

More specifically: we want to redact some variables based on their name, because they can contain sensitive user data. For instance, `content` or `*_token` are replaced by "******" in our current system and in Sentry, and I'd like to do the same with stackprinter.

Is there already a way to do that? If not, what would be a good way to add such a filter?

Thanks!

**Comment by Mcsavvy** [comment]
You should consider forking this repo.

**Comment by ale-dd** [comment]
I have the same needs. Certain variables and dictionary fields in my software contain full blown URLs. I already feed them through a function of mine that redact the passwords, but they are now creeping up in these stack traces. @Schnouki what did you end up doing?

**Comment by cknd** [comment]
This will be in the next release :) https://github.com/cknd/stackprinter/pull/51

**Comment by cknd** [comment]
I just pushed the new version 0.2.6 to pypi, try `pip install -U stackprinter` and then there is the option to say `stackprinter.format(suppressed_vars=[r".*token.*"])`) etc

**Comment by cknd** [comment]
Link to the new docs https://github.com/cknd/stackprinter/pull/51/files#diff-91da0cc91398ea49c7111d1e47ce703e5ae297ed7ff2daf87625dc83a8fd6841

**Comment by cknd** [comment]
feel free to reopen if it doesn't fully adress the issue!
