### ISSUE TITLE
Don't assume `sys.stderr` is always present

### ISSUE THREAD

**Issue by aivarannamaa** [cknd/stackprinter#55]
`TracePrinter`'s constructor's default value for `print_function` assumes `sys.stderr` is present https://github.com/cknd/stackprinter/blob/f91f15b54589fa28e6a6b4b638968fc5c846c363/stackprinter/tracing.py#L82

but this is not the case when the program is run on Windows via pythonw.exe, therefore importing this module would give an exception (see https://groups.google.com/g/thonny/c/KuGZsl717_k for an example case).

**Comment by cknd** [comment]
Hey, interesting edge case - I'll push a fix soon, shouldn't be too hard

**Comment by cknd** [comment]
Hi there! This should be fixed in version 0.2.7, which I've pushed to PyPI just now :)
