### ISSUE TITLE
Can't accept non-string multiline tokens

### ISSUE THREAD

**Issue by ale-dd** [cknd/stackprinter#68]
Recently, quite often I end up struggling with this error:

```Stackprinter failed:
  File "venv312/lib/python3.12/site-packages/stackprinter/source_inspection.py", line 151, in _tokenize
    assert sline == eline, "Can't accept non-string multiline tokens"
AssertionError: Can't accept non-string multiline tokens```

Any hint as to what may be going on?

**Comment by ale-dd** [comment]
It happens in so many places I don't think it's a "local" problem. I wonder if it might have to do with the order of imports and with the use of asyncio + threadpools + nest_asyncio + uvloop?

**Comment by cknd** [comment]
can you give me access to a piece of code on which I can reproduce the problem?

**Comment by cknd** [comment]
(I can't guess the underlting bug, I need to see it fail and look at the error traces and steo through with a debugger)

**Comment by cknd** [comment]
This was surprisingly simple in the end -- it should work now with version [0.2.12](https://pypi.org/project/stackprinter/0.2.12/)
